

export default {
    //购物车-- 加
    CART_AMOUNT_INCREMENT: 'CART_AMOUNT_INCREMENT',
    //购物车-- 减
    CART_AMOUNT_DECREMENT: 'CART_AMOUNT_DECREMENT',
    //博客列表
    START_FETCH_BLOG_LIST:'START_FETCH_BLOG_LIST',
    FETCH_BLOG_LIST_SUCCESS:'FETCH_BLOG_LIST_SUCCESS',
    FETCH_BLOG_LIST_FAILED:'FETCH_BLOG_LIST_FAILED',
    MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
    MARK_ALL_NOTIFICATION_AS_READ: 'MARK_ALL_NOTIFICATION_AS_READ',
    START_AS_READ: 'START_AS_READ',
    FINISH_AS_READ: 'FINISH_AS_READ',
    RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED'
}