

export default {
    //购物车-- 加
    CART_AMOUNT_INCREMENT: 'CART_AMOUNT_INCREMENT',
    //购物车-- 减
    CART_AMOUNT_DECREMENT: 'CART_AMOUNT_DECREMENT',
    //博客列表
    START_FETCH_BLOG_LIST:'START_FETCH_BLOG_LIST',
    FETCH_BLOG_LIST_SUCCESS:'FETCH_BLOG_LIST_SUCCESS',
    FETCH_BLOG_LIST_FAILED:'FETCH_BLOG_LIST_FAILED',
}